apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::662040447744:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-C9M5XGF4ITGT
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::662040447744:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-21T10:52:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1397"
  uid: bc45cc36-f471-4cc1-a71e-a976f01d0a95
